import { cn } from '@/lib/utils'
import '@/styles/globals.css'
import Providers from '@/utils/providers'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('w-full min-h-screen', GeistSans.className)}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
